// ============================================================
// data.js — Sleep In My EV  |  sleepinmyev.com
// Single source of truth for mattress and EV data.
// Update once here — all pages update automatically.
// ============================================================


const mattresses = [
  {name:"Tesla Model Y Air Mattress",brand:"Tesla (Official)",type:"Hybrid Foam-Air",price:310,weight_lbs:12,rvalue:3.0,thickness_in:3.12,dimensions:'74.4" x 50.4"',pump_included:true,inflation_time:"Self-inflating (pump recommended first use)",model_y:"Good",model_3:"Poor",ioniq5:"Poor",ev9:"Poor",r1s:"Poor",id4:"Poor",id_buzz:"Poor",ex40:"Poor",ix:"Poor",mach_e:"Poor",bz4x:"Poor",solterra:"Poor",bolt:"Poor",equinox:"Poor",kia_ev6:"Poor",ioniq6:"Poor",model_x:"Poor",r1t:"Poor",rivian_r2:"Poor",polestar2:"Poor",cybertruck:"Poor",f150_lightning:"Poor",id_buzz_tourer:"Poor",ariya:"Poor",blazer_ev:"Poor",ioniq9:"Poor",trailseeker:"Poor",vinfast_vf8:"Poor",vinfast_vf9:"Poor",rating:4.4,best_for:"Tesla Model Y owners wanting the perfect official fit",pros:"Only mattress designed by Tesla — guaranteed perfect fit all Model Y variants; 3-inch high-density foam fill; waterproof polyester; includes pump, carry bag & repair patches; stows in rear well",cons:"Model Y only — useless for other EVs; frequently out of stock; requires Tesla owner account to buy; no R-value published; heavier than pure-air options",ev_note:"The only mattress sold by Tesla itself. Fits snugly across folded rear seats and trunk of all Model Y variants. Designed to stow in the rear well during the day. Pairs perfectly with Camp Mode. Currently CA $310, often out of stock — check Tesla Shop for availability.",range_impact:0.12,buy_url:"https://shop.tesla.com/en_ca/product/model-y-air-mattress"},
  {name:"Luno AIR Pro",brand:"Luno",type:"Inflatable",price:220,weight_lbs:9,rvalue:1.8,thickness_in:4,dimensions:'78" x 52"',pump_included:true,inflation_time:"2 min (12V pump)",model_y:"Good",model_3:"Fair",ioniq5:"Good",ev9:"Fair",r1s:"Fair",id4:"Poor",id_buzz:"Good",ex40:"Fair",ix:"Good",mach_e:"Fair",bz4x:"Fair",solterra:"Fair",bolt:"Fair",equinox:"Poor",kia_ev6:"Poor",ioniq6:"Poor",model_x:"Good",r1t:"Poor",rivian_r2:"Fair",polestar2:"Poor",cybertruck:"Fair",f150_lightning:"Fair",id_buzz_tourer:"Good",ariya:"Good",blazer_ev:"Poor",ioniq9:"Fair",trailseeker:"Fair",vinfast_vf8:"Fair",vinfast_vf9:"Fair",rating:4.7,best_for:"Car camping, SUV-specific fit",pros:"Vehicle-specific design; fits 4000+ models; durable 300D fabric; dual-chamber; 2-min inflate with included 12V pump",cons:"Low R-value (cold nights need Camp Mode); noisy pump; check vehicle compatibility before buying",ev_note:"Best EV pick for Tesla Model Y / Ioniq 5 — vehicle-specific fit maximizes sleeping space. Lightweight at 9 lbs means 0.09% range impact.",range_impact:0.09,buy_url:"https://lunolife.com/products/air-pro-vehicle-mattress"},
  {name:"Luno AIR+FOAM Pro",brand:"Luno",type:"Hybrid Foam-Air",price:340,weight_lbs:14,rvalue:11.2,thickness_in:4,dimensions:'78" x 52"',pump_included:true,inflation_time:"60 sec (self-inflating)",model_y:"Good",model_3:"Fair",ioniq5:"Good",ev9:"Fair",r1s:"Fair",id4:"Poor",id_buzz:"Good",ex40:"Fair",ix:"Good",mach_e:"Fair",bz4x:"Fair",solterra:"Fair",bolt:"Fair",equinox:"Poor",kia_ev6:"Poor",ioniq6:"Poor",model_x:"Good",r1t:"Poor",rivian_r2:"Fair",polestar2:"Poor",cybertruck:"Fair",f150_lightning:"Fair",id_buzz_tourer:"Good",ariya:"Good",blazer_ev:"Poor",ioniq9:"Fair",trailseeker:"Fair",vinfast_vf8:"Fair",vinfast_vf9:"Fair",rating:4.6,best_for:"All-season EV camping, couples",pros:"Warmest on this list (R-11.2); 60-second self-inflate; premium durability; vehicle-specific design",cons:"More expensive than AIR Pro; heavier at 14 lbs; still vehicle-specific (check fit)",ev_note:"Premium EV pick — R-11.2 means you use climate control less overnight, saving battery. Only 14 lbs means 0.14% range impact.",range_impact:0.14,buy_url:"https://lunolife.com/products/air-foam-pro-vehicle-mattress"},
  {name:"Luno AIR Base",brand:"Luno",type:"Inflatable",price:149,weight_lbs:9,rvalue:1.5,thickness_in:4,dimensions:'78" x 52"',pump_included:true,inflation_time:"30 sec per side (12V)",model_y:"Fair",model_3:"Fair",ioniq5:"Good",ev9:"Fair",r1s:"Poor",id4:"Poor",id_buzz:"Good",ex40:"Fair",ix:"Good",mach_e:"Fair",bz4x:"Fair",solterra:"Fair",bolt:"Fair",equinox:"Poor",kia_ev6:"Poor",ioniq6:"Poor",model_x:"Good",r1t:"Poor",rivian_r2:"Fair",polestar2:"Poor",cybertruck:"Fair",f150_lightning:"Fair",id_buzz_tourer:"Good",ariya:"Good",blazer_ev:"Poor",ioniq9:"Fair",trailseeker:"Fair",vinfast_vf8:"Fair",vinfast_vf9:"Poor",rating:4.5,best_for:"Budget EV camping, compact SUVs",pros:"Affordable Luno entry point; fits compact SUVs well; fast inflate; lightweight",cons:"Lower comfort than AIR Pro; minimal insulation; less ideal for large EVs",ev_note:"Budget EV pick — great for Ioniq 5 and compact crossovers. Use with Camp Mode for cold weather camping.",range_impact:0.09,buy_url:"https://www.amazon.com/Luno-AIR-Base-Mattresses-Mattress/dp/B0GLJDCP36"},
  {name:"Therm-a-Rest MondoKing 3D",brand:"Therm-a-Rest",type:"Self-Inflating",price:250,weight_lbs:5.5,rvalue:7.0,thickness_in:4.25,dimensions:'77" x 25" (L) or 80" x 30" (XL)',pump_included:false,inflation_time:"20-30 min self-inflate + 2.5 min pump sack top-up",model_y:"Good",model_3:"Good",ioniq5:"Good",ev9:"Good",r1s:"Good",id4:"Good",id_buzz:"Good",ex40:"Good",ix:"Good",mach_e:"Good",bz4x:"Good",solterra:"Good",bolt:"Good",equinox:"Poor",kia_ev6:"Good",ioniq6:"Good",model_x:"Good",r1t:"Good",rivian_r2:"Good",polestar2:"Good",cybertruck:"Good",f150_lightning:"Good",id_buzz_tourer:"Good",ariya:"Good",blazer_ev:"Poor",ioniq9:"Good",trailseeker:"Good",vinfast_vf8:"Good",vinfast_vf9:"Good",rating:4.8,best_for:"Best comfort, solo sleepers, all-season",pros:"#1 rated comfort in multiple tests; warm (R-7.0); surprisingly light at 5.5 lbs; TwinLock dual valve; Made in USA; StrataCore construction",cons:"Solo only — no double size available; bulky when packed; expensive for solo use",ev_note:"Best value for solo EV campers — lightest high-quality mattress at 5.5 lbs (0.055% range). R-7.0 means good warmth with reduced climate control drain overnight.",range_impact:0.055,buy_url:"https://www.rei.com/product/241042/therm-a-rest-mondoking-3d-sleeping-pad"},
  {name:"Exped MegaMat Duo 10",brand:"Exped",type:"Self-Inflating",price:420,weight_lbs:9.9,rvalue:8.1,thickness_in:4,dimensions:'77.6" x 52"',pump_included:true,inflation_time:"20 min self-inflate + top-up pump",model_y:"Good",model_3:"Poor",ioniq5:"Fair",ev9:"Good",r1s:"Good",id4:"Poor",id_buzz:"Good",ex40:"Poor",ix:"Good",mach_e:"Poor",bz4x:"Poor",solterra:"Poor",bolt:"Poor",equinox:"Poor",kia_ev6:"Poor",ioniq6:"Poor",model_x:"Good",r1t:"Poor",rivian_r2:"Poor",polestar2:"Poor",cybertruck:"Good",f150_lightning:"Good",id_buzz_tourer:"Good",ariya:"Fair",blazer_ev:"Poor",ioniq9:"Good",trailseeker:"Poor",vinfast_vf8:"Poor",vinfast_vf9:"Good",rating:4.7,best_for:"Couples, luxury EV camping, cold weather",pros:"Exceptional comfort for two; high R-8.1; 30% more foam coring for better deflation; 75D durable base; side handles",cons:"Expensive; heaviest on list at 9.9 lbs; slow to inflate; bulky packed; Ioniq 5 fit is fair (check dimensions)",ev_note:"Best couples pick for larger EVs (EV9, R1S, Model Y). R-8.1 reduces overnight climate control use. At 9.9 lbs, range impact is just 0.099%.",range_impact:0.099,buy_url:"https://www.rei.com/product/113720/exped-megamat-duo-10-sleeping-pad"},
  {name:"NEMO Roamer Double",brand:"NEMO",type:"Self-Inflating",price:430,weight_lbs:6.2,rvalue:7.0,thickness_in:4,dimensions:'78" x 52"',pump_included:true,inflation_time:"Fastest self-inflate tested; Vortex pump sack",model_y:"Good",model_3:"Poor",ioniq5:"Good",ev9:"Good",r1s:"Good",id4:"Poor",id_buzz:"Good",ex40:"Poor",ix:"Good",mach_e:"Poor",bz4x:"Poor",solterra:"Poor",bolt:"Poor",equinox:"Poor",kia_ev6:"Poor",ioniq6:"Poor",model_x:"Good",r1t:"Poor",rivian_r2:"Poor",polestar2:"Poor",cybertruck:"Good",f150_lightning:"Good",id_buzz_tourer:"Good",ariya:"Good",blazer_ev:"Poor",ioniq9:"Good",trailseeker:"Poor",vinfast_vf8:"Poor",vinfast_vf9:"Good",rating:4.6,best_for:"Couples wanting lighter option, 3-season",pros:"Lighter than MegaMat Duo at 6.2 lbs; R-7.0 matches MondoKing; fastest self-inflate of tested pads; Vortex pump sack; premium recycled 50+75D materials; dual storage bags (stuff sack + duffel)",cons:"Noticeable motion transfer for couples; pricey at $430; can be tough to re-pack tightly; only 1 review on REI as of mid-2026 — newer product",ev_note:"Lighter couples option vs MegaMat — 2.4 lb saving (0.075% vs 0.099% range). Choose if weight matters more than warmth; use Camp Mode in winter.",range_impact:0.075,buy_url:"https://www.rei.com/product/C01319/nemo-roamer-self-inflating-sleeping-pad-double"},
  {name:"Sea to Summit Comfort Deluxe LW",brand:"Sea to Summit",type:"Self-Inflating",price:250,weight_lbs:5.2,rvalue:6.5,thickness_in:3.9,dimensions:'79" x 29"',pump_included:false,inflation_time:"Fastest self-inflate of any tested (Delta Core foam tech)",model_y:"Good",model_3:"Good",ioniq5:"Good",ev9:"Good",r1s:"Good",id4:"Good",id_buzz:"Good",ex40:"Good",ix:"Good",mach_e:"Good",bz4x:"Good",solterra:"Good",bolt:"Good",equinox:"Good",kia_ev6:"Good",ioniq6:"Good",model_x:"Good",r1t:"Good",rivian_r2:"Good",polestar2:"Good",cybertruck:"Good",f150_lightning:"Good",id_buzz_tourer:"Good",ariya:"Good",blazer_ev:"Good",ioniq9:"Good",trailseeker:"Good",vinfast_vf8:"Good",vinfast_vf9:"Good",rating:4.7,best_for:"Solo EV campers wanting lightweight + warmth balance",pros:"Lightest quality self-inflating (5.2 lbs); fastest self-inflate tested; Delta Core foam; pillow-lock system; 75D base",cons:"No pump sack included; tricky to repack into stuff sack; narrower at 29 in vs 30 in competitors",ev_note:"Best lightweight self-inflating — 5.2 lbs = 0.052% range impact. Great R-6.5 means good cold weather performance even without constant Camp Mode.",range_impact:0.052,buy_url:"https://www.rei.com/product/206802/sea-to-summit-comfort-deluxe-self-inflating-sleeping-pad"},
  {name:"Klymit Klymaloft Double",brand:"Klymit",type:"Hybrid Foam-Air",price:200,weight_lbs:6.0,rvalue:2.1,thickness_in:5,dimensions:'78" x 53"',pump_included:false,inflation_time:"Manual or Klymit USB pump (sold separately)",model_y:"Good",model_3:"Poor",ioniq5:"Good",ev9:"Good",r1s:"Good",id4:"Poor",id_buzz:"Good",ex40:"Poor",ix:"Good",mach_e:"Poor",bz4x:"Fair",solterra:"Fair",bolt:"Poor",equinox:"Poor",kia_ev6:"Poor",ioniq6:"Poor",model_x:"Good",r1t:"Poor",rivian_r2:"Poor",polestar2:"Poor",cybertruck:"Good",f150_lightning:"Good",id_buzz_tourer:"Good",ariya:"Good",blazer_ev:"Poor",ioniq9:"Good",trailseeker:"Fair",vinfast_vf8:"Poor",vinfast_vf9:"Good",rating:4.4,best_for:"Budget couples, summer EV camping with Camp Mode",pros:"Thickest on list at 5 inches; affordable for doubles; memory foam top layer; lightweight at 6 lbs for a couples pad",cons:"Low R-2.1 — needs Camp Mode in cold weather; no pump included; long-term durability unknown; budget brand",ev_note:"Budget couples pick — R-2.1 is fine with Camp Mode running. At 6 lbs, range impact is just 0.06%. Best value for summer EV camping.",range_impact:0.06,buy_url:"https://www.amazon.com/KLYMALOFT-Sleeping-Revolutionary-Ultra-thick-Backpacking/dp/B08VLWYTD9"},
  {name:"NEMO Eclipse All-Season",brand:"NEMO",type:"Inflatable",price:200,weight_lbs:1.5,rvalue:6.2,thickness_in:4.0,dimensions:'76" x 25"',pump_included:true,inflation_time:"Fast — Vortex pump sack included",model_y:"Good",model_3:"Good",model_x:"Good",cybertruck:"Good",ioniq5:"Good",ioniq6:"Good",ev9:"Good",kia_ev6:"Good",r1s:"Good",r1t:"Good",rivian_r2:"Good",id4:"Good",id_buzz:"Good",id_buzz_tourer:"Good",ex40:"Good",ix:"Good",mach_e:"Good",f150_lightning:"Good",bz4x:"Good",solterra:"Good",bolt:"Good",equinox:"Good",polestar2:"Good",ariya:"Good",blazer_ev:"Good",ioniq9:"Good",trailseeker:"Good",vinfast_vf8:"Good",vinfast_vf9:"Good",rating:4.8,best_for:"Ultralight solo, all-season EV camping, backpack crossover",pros:"Replaces discontinued Quasar 3D; R-6.2 all-season warmth; 4\" thick (thickest NEMO air pad); only 1.5 lbs; vertical Spaceframe baffles cradle body; Thermal Mirror insulation silent (no crinkle); Vortex pump sack; 40D nylon both sides; NEMO Lifetime Warranty",cons:"Air pad — puncture risk vs foam alternatives; narrow 25\" width (solo only); relatively new product (2026) so long-term durability unproven",ev_note:"Direct replacement for the discontinued Quasar 3D — same pack size, same ultralight weight, but upgraded with R-6.2 warmth and 4\" thickness. At 1.5 lbs it\'s the lightest mattress on this list (0.015% range impact). Perfect for EV campers doing multi-sport trips mixing backpacking and car camping.",range_impact:0.015,buy_url:"https://www.rei.com/product/C01317/nemo-eclipse-all-season-sleeping-pad"},

  {name:"HEST Foamy Wide",brand:"HEST",type:"Foam (Memory)",price:329,weight_lbs:13,rvalue:8.8,thickness_in:3.9,dimensions:'78" x 30"',pump_included:false,inflation_time:"None — unroll and sleep (30 seconds)",model_y:"Good",model_3:"Good",model_x:"Good",cybertruck:"Good",ioniq5:"Good",ioniq6:"Good",ev9:"Good",kia_ev6:"Good",r1s:"Good",r1t:"Good",rivian_r2:"Good",id4:"Good",id_buzz:"Good",id_buzz_tourer:"Good",ex40:"Good",ix:"Good",mach_e:"Good",f150_lightning:"Good",bz4x:"Good",solterra:"Good",bolt:"Good",equinox:"Good",polestar2:"Good",ariya:"Good",blazer_ev:"Good",ioniq9:"Good",trailseeker:"Good",vinfast_vf8:"Good",vinfast_vf9:"Good",rating:4.8,best_for:"Solo comfort-first, all-season, zero-fuss setup",pros:"No inflation ever needed — unroll and sleep; top-rated comfort (CleverHiker, Better Trail, OGL); R-8.8 warmth; machine-washable cover; phone pocket; links to other Foamys; can\'t puncture",cons:"Heaviest solo pad on this list at 13 lbs; very bulky packed; foam compresses over time (durability reports mixed); US-only shipping; expensive for solo",ev_note:"The zero-inflation story is unique for EV camping — arrive, unroll, sleep. R-8.8 means Camp Mode works less hard overnight saving battery. At 13 lbs range impact is 0.13% — still trivial. Best for large EVs with room for the bulky roll.",range_impact:0.13,buy_url:"https://www.rei.com/product/203057/hest-foamy-sleeping-pad"},
  {name:"HEST Dually Long",brand:"HEST",type:"Foam (Memory)",price:589,weight_lbs:22,rvalue:8.5,thickness_in:3.9,dimensions:'78" x 50"',pump_included:false,inflation_time:"None — unfold and sleep",model_y:"Good",model_3:"Poor",model_x:"Good",cybertruck:"Good",ioniq5:"Fair",ioniq6:"Poor",ev9:"Good",kia_ev6:"Poor",r1s:"Good",r1t:"Good",rivian_r2:"Poor",id4:"Poor",id_buzz:"Good",id_buzz_tourer:"Good",ex40:"Poor",ix:"Poor",mach_e:"Poor",f150_lightning:"Good",bz4x:"Poor",solterra:"Poor",bolt:"Poor",equinox:"Poor",polestar2:"Poor",ariya:"Fair",blazer_ev:"Poor",ioniq9:"Good",trailseeker:"Poor",vinfast_vf8:"Poor",vinfast_vf9:"Good",rating:4.7,best_for:"Couples, premium comfort, large EVs and truck beds",pros:"No inflation needed for two people; premium memory foam couples comfort; virtually can\'t puncture; folds flat for vehicle storage; halves stay seamless; washable cover",cons:"Most expensive mattress on this list ($529-629); heaviest at 22 lbs; very bulky folded; foam compression over time; US-only shipping; too wide for most compact EVs",ev_note:"Ultimate no-fuss couples setup — unfold and sleep, no pump, no inflation. At 50\" wide fits Model Y, EV9, R1S, Model X, ID.Buzz, Cybertruck, F-150. Too wide for narrower EVs. Weight is 22 lbs (0.22% range impact) — manageable for the comfort.",range_impact:0.22,buy_url:"https://hest.com/products/dually"},
  {name:"REI Westward Dreamer",brand:"REI Co-op",type:"Self-Inflating",price:199,weight_lbs:6.7,rvalue:6.7,thickness_in:4.0,dimensions:'76" x 25"',pump_included:false,inflation_time:"15-20 min self-inflate + manual top-up",model_y:"Good",model_3:"Good",model_x:"Good",cybertruck:"Good",ioniq5:"Good",ioniq6:"Good",ev9:"Good",kia_ev6:"Good",r1s:"Good",r1t:"Good",rivian_r2:"Good",id4:"Good",id_buzz:"Good",id_buzz_tourer:"Good",ex40:"Good",ix:"Good",mach_e:"Good",f150_lightning:"Good",bz4x:"Good",solterra:"Good",bolt:"Good",equinox:"Good",polestar2:"Good",ariya:"Good",blazer_ev:"Good",ioniq9:"Good",trailseeker:"Good",vinfast_vf8:"Good",vinfast_vf9:"Good",rating:4.5,best_for:"Budget-conscious solo EV campers, 3-season",pros:"GearJunkie 2026 budget winner; R-6.7 excellent for price; 4\" thick; repair kit included; available in all REI stores; trusted returns policy; good value",cons:"Thinner 30D top material feels plasticky vs premium pads; not as plush as MondoKing; solo 25\" width only; self-inflation slow",ev_note:"Best budget self-inflating for solo EV campers — GearJunkie\'s 2026 budget winner at $199. R-6.7 good cold weather performance even without Camp Mode. 6.7 lbs (0.067% range impact). Widely available at REI stores for easy in-person purchase and easy returns.",range_impact:0.067,buy_url:"https://www.rei.com/search?q=westward+dreamer"},
  {name:"Exped DeepSleep Mat",brand:"Exped",type:"Self-Inflating",price:190,weight_lbs:4.4,rvalue:9.0,thickness_in:3.0,dimensions:'77.6" x 25.6"',pump_included:true,inflation_time:"Self-inflate + included Top-Up Pump",model_y:"Good",model_3:"Good",model_x:"Good",cybertruck:"Good",ioniq5:"Good",ioniq6:"Good",ev9:"Good",kia_ev6:"Good",r1s:"Good",r1t:"Good",rivian_r2:"Good",id4:"Good",id_buzz:"Good",id_buzz_tourer:"Good",ex40:"Good",ix:"Good",mach_e:"Good",f150_lightning:"Good",bz4x:"Good",solterra:"Good",bolt:"Good",equinox:"Good",polestar2:"Good",ariya:"Good",blazer_ev:"Good",ioniq9:"Good",trailseeker:"Good",vinfast_vf8:"Good",vinfast_vf9:"Good",rating:4.6,best_for:"Cold-weather EV camping, back sleepers, warmth on a budget",pros:"Highest R-value on this entire list (R-9.0); $70 less than MegaMat; 4.4 lbs extremely light for the warmth; recycled 75D polyester; PFAS-free; solid foam — can\'t puncture; includes Top-Up Pump",cons:"Only 3\" thick — firmer feel better for back than side sleepers; narrower at 25.6\"; O-ring valve complaints in some reviews; lower profile less plush than MegaMat",ev_note:"Best R-value per dollar on this list — R-9.0 at $190 means serious cold weather capability. At 4.4 lbs one of the lightest quality pads we cover (0.044% range impact). Excellent for EV campers wanting warmth without draining Camp Mode battery. Firm 3\" feel suits flat EV cargo floors.",range_impact:0.044,buy_url:"https://www.rei.com/product/238241/exped-deepsleep-sleeping-pad"},
  {name:"Klymit Insulated Double V",brand:"Klymit",type:"Inflatable",price:140,weight_lbs:3.6,rvalue:4.4,thickness_in:3.0,dimensions:'74" x 47"',pump_included:false,inflation_time:"30-40 breaths manual; fast deflation",model_y:"Good",model_3:"Poor",model_x:"Good",cybertruck:"Good",ioniq5:"Good",ioniq6:"Poor",ev9:"Good",kia_ev6:"Poor",r1s:"Good",r1t:"Good",rivian_r2:"Fair",id4:"Poor",id_buzz:"Good",id_buzz_tourer:"Good",ex40:"Poor",ix:"Poor",mach_e:"Poor",f150_lightning:"Good",bz4x:"Poor",solterra:"Poor",bolt:"Poor",equinox:"Fair",polestar2:"Poor",ariya:"Good",blazer_ev:"Fair",ioniq9:"Good",trailseeker:"Poor",vinfast_vf8:"Poor",vinfast_vf9:"Good",rating:4.3,best_for:"Budget couples, multi-use (camping + backpacking), lightest double",pros:"Lightest double pad on entire list at 3.6 lbs; most packable couples option; budget at $140; R-4.4 covers 3-season; V-weld design stops cold air circulation; field repair kit included",cons:"Less comfortable than foam alternatives; manual inflation only (30-40 breaths); OGL noted as least comfortable couples pad in comparison; R-4.4 marginal in extreme cold without Camp Mode",ev_note:"Lightest double at 3.6 lbs (0.036% range impact) — ideal for couples who also hike or backpack. At 47\" wide fits most large EVs. With Camp Mode handling warmth, R-4.4 is adequate year-round for EV camping. Budget king for couples.",range_impact:0.036,buy_url:"https://www.amazon.com/dp/B07YP8TXVR"},
  {name:"REI Co-op Campwell",brand:"REI Co-op",type:"Self-Inflating",price:129,weight_lbs:3.5,rvalue:7.0,thickness_in:2.5,dimensions:'72" x 25"',pump_included:false,inflation_time:"10-15 min self-inflate",model_y:"Good",model_3:"Good",model_x:"Good",cybertruck:"Good",ioniq5:"Good",ioniq6:"Good",ev9:"Good",kia_ev6:"Good",r1s:"Good",r1t:"Good",rivian_r2:"Good",id4:"Good",id_buzz:"Good",id_buzz_tourer:"Good",ex40:"Good",ix:"Good",mach_e:"Good",f150_lightning:"Good",bz4x:"Good",solterra:"Good",bolt:"Good",equinox:"Good",polestar2:"Good",ariya:"Good",blazer_ev:"Good",ioniq9:"Good",trailseeker:"Good",vinfast_vf8:"Good",vinfast_vf9:"Good",rating:4.4,best_for:"Budget solo, cold-weather camping, value-first shoppers",pros:"Best R-value per dollar on this list (R-7.0 at $129); CleverHiker and Switchback Travel budget pick; soft stretch polyester top; toggles connect two pads for couples; Campmor and Reddit owners confirm use to -5°F",cons:"Thinnest pad at 2.5 inches — side sleepers may notice; sloped sides reduce usable surface area; not as plush as MondoKing; REI membership recommended for returns",ev_note:"Best budget pick for EV campers — R-7.0 at $129 is extraordinary value. At 3.5 lbs (0.035% range impact) it's one of the lightest pads on this list. Two Campwells connected cost $258 total vs $420 for the Exped MegaMat — a genuine budget couples solution for wider EVs.",range_impact:0.035,buy_url:"https://www.rei.com/product/228267/rei-co-op-campwell-sleeping-pad"},
  {name:"Sea to Summit Camp Plus",brand:"Sea to Summit",type:"Self-Inflating",price:100,weight_lbs:3.0,rvalue:4.3,thickness_in:3.0,dimensions:'72" x 25"',pump_included:false,inflation_time:"8-12 min self-inflate",model_y:"Good",model_3:"Good",model_x:"Good",cybertruck:"Good",ioniq5:"Good",ioniq6:"Good",ev9:"Good",kia_ev6:"Good",r1s:"Good",r1t:"Good",rivian_r2:"Good",id4:"Good",id_buzz:"Good",id_buzz_tourer:"Good",ex40:"Good",ix:"Good",mach_e:"Good",f150_lightning:"Good",bz4x:"Good",solterra:"Good",bolt:"Good",equinox:"Good",polestar2:"Good",ariya:"Good",blazer_ev:"Good",ioniq9:"Good",trailseeker:"Good",vinfast_vf8:"Good",vinfast_vf9:"Good",rating:4.2,best_for:"3-season budget solo, lightweight camping, first-time EV campers",pros:"CleverHiker best budget badge; 3 inches thick for the price; R-4.3 handles 3-season camping well; Sea to Summit durability track record; packs smallest of any self-inflating here; good for mild/warm weather camping",cons:"R-3.3 limits cold weather use (not suitable below ~40°F without Camp Mode); thinner feel at 2 inches; not ideal for side sleepers on hard surfaces; upgrade recommended if camping below freezing",ev_note:"Ideal entry-level pad for EV campers trying overnight camping for the first time. With Camp Mode or Utility Mode handling warmth, the lower R-3.3 is adequate for 3-season camping. At 2.2 lbs (0.022% range impact) it is the lightest mattress on the entire list.",range_impact:0.03,buy_url:"https://www.rei.com/product/188372/sea-to-summit-camp-plus-self-inflating-sleeping-pad-rectangular"},
  {name:"FULI Japanese Shikibuton",brand:"FULI",type:"Foam",price:120,weight_lbs:8.0,rvalue:1.5,thickness_in:2.0,dimensions:'79" x 39"',pump_included:false,inflation_time:"Ready to use — no setup",model_y:"Good",model_3:"Good",model_x:"Good",cybertruck:"Good",ioniq5:"Good",ioniq6:"Good",ev9:"Good",kia_ev6:"Good",r1s:"Good",r1t:"Good",rivian_r2:"Good",id4:"Good",id_buzz:"Good",id_buzz_tourer:"Good",ex40:"Good",ix:"Good",mach_e:"Good",f150_lightning:"Good",bz4x:"Good",solterra:"Good",bolt:"Fair",equinox:"Good",polestar2:"Good",ariya:"Good",blazer_ev:"Good",ioniq9:"Good",trailseeker:"Good",vinfast_vf8:"Good",vinfast_vf9:"Good",rating:4.3,best_for:"3-season solo or couple, minimalist camping, warm-weather EV camping",pros:"Genuine shikibuton made in Japan; no pump or inflation needed; rolls up in seconds; 100% cotton breathable surface; 8 lbs; very quiet",cons:"R-1.5 means cold without Camp Mode; 2 inches thin; cover sold separately",ev_note:"The zero-setup option for EV campers. At 79in fits anyone under 6ft6in. Requires Camp Mode below 15C.",range_impact:0.08,buy_url:"https://www.amazon.com/dp/B07JJ4TJ4B"},
  {name:"D&D Futon Trifold Shikibuton",brand:"D&D Futon",type:"Foam",price:75,weight_lbs:10.0,rvalue:2.0,thickness_in:6.0,dimensions:'75" x 39"',pump_included:false,inflation_time:"Ready to use — unfold flat",model_y:"Good",model_3:"Good",model_x:"Good",cybertruck:"Good",ioniq5:"Good",ioniq6:"Good",ev9:"Good",kia_ev6:"Good",r1s:"Good",r1t:"Good",rivian_r2:"Good",id4:"Good",id_buzz:"Good",id_buzz_tourer:"Good",ex40:"Good",ix:"Good",mach_e:"Good",f150_lightning:"Good",bz4x:"Good",solterra:"Good",bolt:"Fair",equinox:"Good",polestar2:"Good",ariya:"Good",blazer_ev:"Good",ioniq9:"Good",trailseeker:"Good",vinfast_vf8:"Good",vinfast_vf9:"Good",rating:4.0,best_for:"Budget EV camping, 3-season use, no-inflation camping",pros:"Most affordable non-inflatable; 6 inches thick; CertiPUR-US certified; trifolds compactly; no pump needed; made in USA",cons:"R-2.0 limits cold use; 10 lbs heavier than air pads; 75in length suits campers under 6ft2in",ev_note:"Cheapest non-inflatable on the list. Unfolds flat instantly. 6 inches of foam provides real cushioning. At 39in wide fits most EVs.",range_impact:0.10,buy_url:"https://www.amazon.com/dp/B00A0X6ACY"}
];


// ===== HEIGHT-BASED EV RECOMMENDER =====
// sleeping length in cm (converted from inches), best solo mattresses per EV
const evHeightData = [
  {key:'id_buzz', name:'VW ID.Buzz LWB',      L_cm:221, W_cm:135, H_cm:140, camp:'No',  color:'#0066cc', mat:'Exped MegaMat Duo / NEMO Roamer',  note:'Standard trim — leave climate on manually or use app timer hack. Van-like 55" headroom, best sleeping space of 23 EVs.'},
  {key:'id_buzz_tourer',name:'VW ID.Buzz Tourer 2027',L_cm:221,W_cm:135,H_cm:140,camp:'Yes', color:'#0044aa', mat:'VW factory mattress (included) / Exped MegaMat Duo', note:'Overnight Mode: full climate for up to 48hrs. ~4-8% battery/night (mild), ~15-18% (cold winter). Factory mattress + privacy shades included. No V2L.'},
  {key:'ev9',     name:'Kia EV9',             L_cm:206, W_cm:132, H_cm:102, camp:'Yes', color:'#c47a00', mat:'Exped MegaMat Duo / Luno AIR+FOAM', note:'Largest SUV sleeping area. Remove 3rd row.'},
  {key:'r1s',     name:'Rivian R1S',          L_cm:213, W_cm:127, H_cm:102, camp:'Yes', color:'#2a6e2a', mat:'Exped MegaMat Duo / MondoKing 3D',  note:'Air suspension levels the platform. 11 cu ft gear tunnel.'},
  {key:'model_y', name:'Tesla Model Y',       L_cm:193, W_cm:132, H_cm: 94, camp:'Yes', color:'#0f6e56', mat:'Luno AIR Pro / MondoKing 3D',       note:'Best all-round EV camper. Near-flat floor, frunk storage.'},
  {key:'ix',      name:'BMW iX',              L_cm:191, W_cm:109, H_cm: 97, camp:'No',  color:'#333',    mat:'MondoKing 3D / S2S Comfort Deluxe',  note:'No frunk. Tight width at wheel wells (~41").'},
  {key:'mach_e',  name:'Ford Mustang Mach-E', L_cm:173, W_cm:112, H_cm: 86, camp:'No',  color:'#b03060', mat:'MondoKing 3D / NEMO Eclipse All-Season',     note:'Frunk adds 4.8 cu ft storage. Sloping roofline.'},
  {key:'equinox', name:'Chevrolet Equinox EV',L_cm:173, W_cm:114, H_cm: 89, camp:'No',  color:'#c4a000', mat:'MondoKing 3D / S2S Comfort Deluxe',  note:'Dual-height cargo floor. Good value mid-size.'},
  {key:'ioniq5',  name:'Hyundai Ioniq 5',     L_cm:185, W_cm:119, H_cm: 91, camp:'Yes', color:'#1a6eb5', mat:'Luno AIR Pro / NEMO Roamer Double',  note:'Flattest floor of all EVs. V2L exports 1.9kW.'},
  {key:'bz4x',    name:'Toyota bZ4X',         L_cm:185, W_cm:114, H_cm: 91, camp:'No',  color:'#cc3300', mat:'MondoKing 3D / NEMO Eclipse All-Season',     note:'Adjustable deckboard helps flatten floor.'},
  {key:'solterra',name:'Subaru Solterra',     L_cm:185, W_cm:114, H_cm: 91, camp:'No',  color:'#1a5c8a', mat:'MondoKing 3D / NEMO Eclipse All-Season',     note:'Identical platform to bZ4X. Standard AWD.'},
  {key:'ex40',    name:'Volvo EX40',          L_cm:170, W_cm:112, H_cm: 86, camp:'No',  color:'#1c6b8a', mat:'MondoKing 3D / NEMO Eclipse All-Season',     note:'Small step at hinge — thin platform recommended.'},
  {key:'id4',     name:'VW ID.4',             L_cm:196, W_cm: 94, H_cm: 81, camp:'No',  color:'#555',    mat:'MondoKing 3D (25" wide) / NEMO Eclipse (25" wide)',  note:'77" long (owner verified) — fits to 6\'4"! But only 37" wide: solo thin pads only. Platform needed for floor step.'},
  {key:'model_3', name:'Tesla Model 3',       L_cm:183, W_cm:107, H_cm: 53, camp:'Yes', color:'#cc3333', mat:'NEMO Eclipse All-Season / S2S Comfort Deluxe',note:'Only 21" headroom. Cannot sit up. Solo only.'},
  {key:'bolt',    name:'Chevrolet Bolt EV',   L_cm:152, W_cm:107, H_cm: 84, camp:'No',  color:'#cc6600', mat:'NEMO Eclipse All-Season / S2S Comfort Deluxe',note:'Shortest sleeping space. Best for under 5\'8".'},
  {key:'kia_ev6',      name:'Kia EV6',               L_cm:165, W_cm:109, H_cm: 66, camp:'Yes', color:'#cc3300', mat:'NEMO Eclipse All-Season / S2S Comfort Deluxe',  note:'Utility Mode keeps climate running overnight (~6% battery/8hrs). V2L 3.6kW highest on list. 65" length best for under 5\'11".'},
  {key:'ioniq6',       name:'Hyundai Ioniq 6',        L_cm:180, W_cm:109, H_cm: 58, camp:'Yes', color:'#2a78d6', mat:'NEMO Eclipse All-Season / S2S Comfort Deluxe',  note:'Utility Mode runs climate overnight (same as Camp Mode). Sedan — low headroom 23". V2L 3.6kW for external gear.'},
  {key:'model_x',      name:'Tesla Model X',          L_cm:188, W_cm:130, H_cm:102, camp:'Yes', color:'#0f6e56', mat:'Exped MegaMat Duo / Luno AIR+FOAM Pro', note:'3-row SUV — largest Tesla. Falcon-wing doors for easy loading. 6.5 cu ft frunk. Camp Mode all night.'},
  {key:'r1t',          name:'Rivian R1T (Truck Bed)', L_cm:137, W_cm:127, H_cm: 51, camp:'Yes', color:'#2a6e2a', mat:'MondoKing 3D / NEMO Eclipse All-Season',          note:'Truck bed setup (54"L under tonneau). Tailgate-down = 84". Gear Tunnel 11 cu ft. Unique EV truck camping.'},
  {key:'rivian_r2',    name:'Rivian R2',              L_cm:190, W_cm:104, H_cm: 81, camp:'Yes', color:'#3a8e3a', mat:'MondoKing 3D / S2S Comfort Deluxe',      note:'Compact Rivian — 29" hatch opening is narrow. 5.2 cu ft frunk. Camp Mode standard. Budget adventure EV.'},
  {key:'polestar2',    name:'Polestar 2',             L_cm:175, W_cm:104, H_cm: 76, camp:'No',  color:'#1a1a1a', mat:'NEMO Eclipse All-Season / S2S Comfort Deluxe',   note:'Premium hatchback — 69" usable length, 41" wide at wheel wells. Solo camping workable. Small frunk.'},
  {key:'cybertruck',   name:'Tesla Cybertruck',       L_cm:183, W_cm:122, H_cm:102, camp:'Yes', color:'#555',    mat:'MondoKing 3D / NEMO Roamer Double',       note:'Truck bed: 72"L × 48"W. Camp Mode + 120V/240V outlets. Stainless vault bed. V2L capable.'},
  {key:'f150_lightning',name:'Ford F-150 Lightning',  L_cm:163, W_cm:133, H_cm: 89, camp:'Yes', color:'#003399', mat:'MondoKing 3D / NEMO Roamer Double',      note:'Full-size truck: 64"L × 52"W bed. 7.2kW Pro Power Onboard — best V2L of any EV. 14.1 cu ft mega frunk.'}
,
  {key:'ariya',name:'Nissan Ariya',L_cm:183,W_cm:119,H_cm:91,camp:'No',color:'#c41c21',mat:'MondoKing 3D / REI Westward Dreamer',note:'~72in L x 47in W. No Camp Mode. Divide-N-Hide cargo system.'},
  {key:'blazer_ev',name:'Chevy Blazer EV',L_cm:183,W_cm:122,H_cm:91,camp:'No',color:'#d4a017',mat:'MondoKing 3D / Klymit Insulated Double V',note:'~72in L x 48in W est. Slight step seats-to-floor. No Camp Mode or V2L.'},
  {key:'ioniq9',name:'Hyundai Ioniq 9',L_cm:216,W_cm:137,H_cm:104,camp:'Yes',color:'#003580',mat:'Exped MegaMat Duo 10 / NEMO Roamer Double',note:'Est. ~85in L x 54in W (3rd row removed). 3.6kW V2L. Relaxation Mode.'},
  {key:'trailseeker',name:'Subaru Trailseeker',L_cm:191,W_cm:117,H_cm:86,camp:'No',color:'#006a4e',mat:'MondoKing 3D / REI Westward Dreamer',note:'Spec-confirmed 75in L x 46in W. Fully flat floor. Touring: 1500W outlet.'},
  {key:'vinfast_vf8',name:'VinFast VF8',L_cm:173,W_cm:117,H_cm:86,camp:'Partial',color:'#00a651',mat:'MondoKing 3D / Klymit Insulated Double V',note:'Est. ~68in L x 46in W. Camp Mode = lights + audio only. Verify dims before buying mattress.'},
  {key:'vinfast_vf9',name:'VinFast VF9',L_cm:198,W_cm:127,H_cm:94,camp:'Partial',color:'#00a651',mat:'Exped MegaMat Duo 10 / NEMO Roamer Double',note:'Est. ~78in L x 50in W (3rd row folded). Camp Mode = lights + audio only. Large 92kWh battery.'}
];

function cmToFtIn(cm){
  const totalIn = Math.round(cm/2.54);
  return `${Math.floor(totalIn/12)}' ${totalIn%12}"`;
}

function getFitRating(heightCm, evLcm){
  const margin = evLcm - heightCm;
  if(margin >= 15) return {label:'Comfortable', cls:'fit-good',  tip:'Plenty of room — you can sleep with legs straight.'};
  if(margin >= 5)  return {label:'Good Fit',    cls:'fit-good',  tip:'Works well. Push front seat forward for extra space.'};
  if(margin >= -5) return {label:'Tight',       cls:'fit-fair',  tip:'Possible with front seats pushed fully forward (+3–5").'};
  return             {label:'Not Recommended', cls:'fit-poor',  tip:'Too short even with seats adjusted. Consider diagonal sleeping.'};
}

function updateHeightRec(){
  const cm = parseInt(document.getElementById('height-slider').value);
  const inches = Math.round(cm/2.54);
  const ft = Math.floor(inches/12), inp = inches%12;
  document.getElementById('height-display').innerHTML =
    `${ft}' ${inp}" &nbsp;<span style="font-size:.9rem;color:var(--text3);font-weight:400">(${cm} cm)</span>`;

  const container = document.getElementById('height-rec-results');

  // Sort: comfortable first, then good fit, then tight, then not recommended
  const order = {Comfortable:0,'Good Fit':1,Tight:2,'Not Recommended':3};
  const sorted = [...evHeightData].sort((a,b)=>{
    const ra = getFitRating(cm,a.L_cm), rb = getFitRating(cm,b.L_cm);
    return (order[ra.label]||3) - (order[rb.label]||3);
  });

  container.innerHTML = sorted.map(ev => {
    const fit = getFitRating(cm, ev.L_cm);
    const campBadge = ev.camp==='Yes'
      ? `<span style="background:var(--success-bg);color:var(--success);padding:.15rem .45rem;border-radius:3px;font-size:.7rem;font-weight:700">✓ Camp Mode</span>`
      : `<span style="background:var(--warn-bg);color:var(--warn);padding:.15rem .45rem;border-radius:3px;font-size:.7rem;font-weight:700">No Camp Mode</span>`;
    const borderCol = fit.label==='Comfortable'||fit.label==='Good Fit' ? ev.color : fit.label==='Tight' ? '#c47a00' : '#ccc';
    return `
      <div style="background:var(--bg);border:2px solid ${borderCol};border-radius:8px;padding:1.1rem;transition:.2s;cursor:pointer" onclick="showPage('compare');onEVSelect('${ev.key}');document.getElementById('f-vehicle').value='${ev.key}'">
        <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:.6rem;gap:.5rem">
          <div style="font-weight:700;font-size:.92rem;color:var(--text)">${ev.name}</div>
          <span class="fit-badge ${fit.cls}" style="white-space:nowrap;font-size:.72rem">${fit.label}</span>
        </div>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:.3rem .75rem;font-size:.8rem;margin-bottom:.65rem">
          <span style="color:var(--text3)">Sleep length</span><strong>${cmToFtIn(ev.L_cm)} (${ev.L_cm} cm)</strong>
          <span style="color:var(--text3)">Headroom</span><strong>${cmToFtIn(ev.H_cm)}</strong>
          <span style="color:var(--text3)">Climate</span>${campBadge}
        </div>
        <div style="font-size:.78rem;color:var(--text3);font-style:italic;margin-bottom:.6rem;line-height:1.4">${fit.tip}</div>
        <div style="border-top:1px solid var(--border);padding-top:.6rem;margin-top:.4rem">
          <div style="font-size:.72rem;font-weight:700;text-transform:uppercase;letter-spacing:.4px;color:var(--text3);margin-bottom:.25rem">Best mattress</div>
          <div style="font-size:.8rem;color:var(--primary);font-weight:600">${ev.mat}</div>
        </div>
        <div style="font-size:.75rem;color:var(--text2);margin-top:.5rem;line-height:1.4">${ev.note}</div>
      </div>`;
  }).join('');
}

// init on load
document.addEventListener('DOMContentLoaded', updateHeightRec);


const evProfiles = {
  model_y:  {name:"Tesla Model Y",  L:76,W:52,H:37,up:30.0,down:76.0,flat:"Nearly flat",platform:false,camp:"✓ Camp Mode",maxMat:'76\"×52\" (83\" w/seats fwd)',frunk:"4.1 cu ft",campBattery:"~4–7% (mild/summer) · ~14–21% (cold winter)",notes:"Best all-round EV camper. Near-flat floor — no platform needed. Front seats can recline for extra length. Frunk frees cargo space for gear.",mattresses:["Luno AIR Pro","Luno AIR+FOAM Pro","Exped MegaMat Duo 10","Therm-a-Rest MondoKing 3D"],setup:"Fold rear seats. No platform needed. Lay mattress directly. Use frunk for shoes/valuables.",color:"#0f6e56"},
  model_3:  {name:"Tesla Model 3",  L:72,W:42,H:21,up:15.0,down:34.0,flat:"Small step",platform:true,camp:"✓ Camp Mode",maxMat:'72\"×40\" (76\" w/seat fwd)',frunk:"3.1 cu ft",campBattery:"~4–7% (mild/summer) · ~14–21% (cold winter)",notes:"Sedan body = low headroom (21\") — cannot sit up inside. Width narrows to 38\" at wheel wells. Solo camping comfortable; couples very tight.",mattresses:["NEMO Eclipse All-Season","Sea to Summit Comfort Deluxe LW","Therm-a-Rest MondoKing 3D"],setup:"Fold rear seats. Use thin foam pad or plywood board to bridge ~1\" step. Solo pads only — double-wide pads are too wide at 42\".",color:"#cc3333"},
  ioniq5:   {name:"Hyundai Ioniq 5",L:73,W:47,H:36,up:27.2,down:59.0,flat:"✓ Fully flat",platform:false,camp:"✓ Utility Mode + V2L 1.9kW",maxMat:'73\"×47\"',frunk:"None",campBattery:"~4–6% (mild/summer) · ~14–21% (cold winter)",notes:"Flattest floor of all EVs — e-GMP platform. No Camp Mode but climate can be left on manually. V2L exports 1.9kW for external devices.",mattresses:["Luno AIR Pro","Luno AIR Base","NEMO Roamer Double","Sea to Summit Comfort Deluxe LW"],setup:"No platform needed. Enable Utility Mode for overnight climate — works same as Tesla Camp Mode. V2L 1.9kW for external heater, cooker, or lights.",color:"#1a6eb5"},
  ev9:      {name:"Kia EV9",        L:81,W:52,H:40,up:20.3,down:97.0,flat:"Flat (3rd row out)",platform:false,camp:"✓ Relaxation Mode",maxMat:'81\"×52\"',frunk:"None",campBattery:"~3–5% (mild/summer) · ~10–16% (cold winter)",notes:"Largest SUV sleeping area of all 14 EVs. 3rd row must be removed or folded. Relaxation Mode reclines all seats. V2L capable. Best for couples.",mattresses:["Exped MegaMat Duo 10","NEMO Roamer Double","Luno AIR+FOAM Pro","Klymit Klymaloft Double"],setup:"Remove or fold 3rd row. 2nd row folds flat. No platform needed. Best EV for couples camping.",color:"#c47a00"},
  r1s:      {name:"Rivian R1S",     L:84,W:51,H:40,up:16.0,down:104.0,flat:"Flat (3rd folded)",platform:false,camp:"✓ Camp Mode + Air Susp.",maxMat:'84\"×51\"',frunk:"11 cu ft gear tunnel",campBattery:"~2–4% (mild/summer) · ~7–12% (cold winter)",notes:"Largest SUV sleeping space after the ID.Buzz — verified 84-85\" length fits any adult height. Air suspension levels platform on uneven ground. 11 cu ft gear tunnel for valuables. Our original 75\" was a big error — the correct figure is from Recharged & Rivian forums.",mattresses:["Exped MegaMat Duo 10","NEMO Roamer Double","Therm-a-Rest MondoKing 3D"],setup:"Fold 3rd row. Air suspension auto-levels. Gear tunnel stores shoes/valuables. Camp Mode maintains climate overnight.",color:"#2a6e2a"},
  id4:      {name:"VW ID.4",        L:77,W:37,H:32,up:30.3,down:64.2,flat:"Step — needs platform",platform:true,camp:"No — leave climate on",maxMat:'75\"×35\" (solo only — 37\" wide)',frunk:"None",campBattery:"~4–7% (mild/summer) · ~14–21% (manual climate)",notes:"Owner-verified: ~77\" length × 37\" width (seats folded). Length fits up to ~6'4\" — better than expected. Width at 37\" is the real constraint: solo sleepers only, no double-wide pads. Floor step at hinge needs a platform board.",mattresses:["Therm-a-Rest MondoKing 3D","NEMO Eclipse All-Season","Sea to Summit Comfort Deluxe LW"],setup:"Owner measured 77\" L × 37\" W. Platform board for floor step (~$20 plywood). 37\" width = solo pads only — even standard double-wide mats (52\") are far too wide. Best pads: MondoKing 3D (25\" wide), NEMO Eclipse (25\" wide), S2S Comfort Deluxe (29\" wide).",color:"#666"},
  id_buzz:  {name:"VW ID.Buzz LWB (standard trim)",L:87,W:53,H:55,up:18.6,down:145.5,flat:"Mostly flat (Multiflex opt.)",platform:false,camp:"No — leave climate on (manual)",maxMat:'85\"×53\"',frunk:"None",campBattery:"~3–6% (mild/summer) · ~12–18% (manual climate)",notes:"Standard trim has no dedicated Overnight Mode — leave climate on manually or schedule via the app departure timer. Van-like 55\" headroom means you can sit up. 3rd row removable. Multiflex board creates perfectly flat platform. For full overnight climate system, choose the 2027 Tourer trim.",mattresses:["Exped MegaMat Duo 10","NEMO Roamer Double","Klymit Klymaloft Double","Luno AIR+FOAM Pro"],setup:"Remove 3rd row. Fold 2nd row. Multiflex board option gives flat surface. Without Overnight Mode, use app departure timer to schedule climate cycles.",color:"#0066cc"},
  id_buzz_tourer:{name:"VW ID.Buzz Tourer (2027)",L:87,W:53,H:55,up:18.6,down:145.5,flat:"Flat (factory bed platform included)",platform:false,camp:"✓ Overnight Mode (48hrs)",maxMat:'VW factory mattress (included)',frunk:"None",campBattery:"~4–7% (mild/summer) · ~12–18% (Overnight Mode)",notes:"First factory EV camping van sold in the US. Overnight Mode runs climate control, USB-C and 12V ports, and lighting for up to 48 hours on the HV battery. Includes fold-out mattress with levelling platform, full magnetic privacy shades, window ventilation panels, outdoor table and chairs. No V2L (cannot power external appliances from charge port).",mattresses:["VW factory mattress (included)","Exped MegaMat Duo 10","NEMO Roamer Double"],setup:"Factory bed platform levels over rear seats. Factory mattress included — no extra purchase needed. Engage Overnight Mode from the infotainment for up to 48hr climate. Add aftermarket mattress topper for extra comfort. Privacy shades included.",color:"#0044aa"},
  ex40:     {name:"Volvo EX40",     L:67,W:44,H:34,up:16.0,down:57.5,flat:"Small step",platform:true,camp:"No — leave climate on",maxMat:'65\"×42\"',frunk:"21L (small)",campBattery:"~5–7% (mild/summer) · ~16–23% (manual climate)",notes:"Compact luxury SUV. 35\" floor length behind rear seats; 67\" total with seats folded. Small frunk (21L). Flat load floor with low lip. Solo camping only.",mattresses:["NEMO Eclipse All-Season","Sea to Summit Comfort Deluxe LW","Therm-a-Rest MondoKing 3D"],setup:"Fold rear seats. Bridge small step with foam or thin board. Solo pads best at 44\" width.",color:"#1c6b8a"},
  ix:       {name:"BMW iX",         L:75,W:43,H:38,up:35.5,down:77.9,flat:"Nearly flat",platform:false,camp:"No — leave climate on",maxMat:'73\"×41\"',frunk:"None",campBattery:"~3–5% (mild/summer) · ~10–14% (manual climate)",notes:"Luxury midsize. 40/20/40 split rear bench. No frunk. Wide boxy cargo opening. Width ~41\" at wheel wells. Solo or very snug couples.",mattresses:["Therm-a-Rest MondoKing 3D","Sea to Summit Comfort Deluxe LW","NEMO Eclipse All-Season"],setup:"Fold all rear seats. No platform needed. Push front seats forward. Width is tight — solo pads recommended.",color:"#333"},
  mach_e:   {name:"Ford Mustang Mach-E",L:68,W:44,H:34,up:29.7,down:59.7,flat:"Small step",platform:false,camp:"No — leave climate on",maxMat:'66\"×42\"',frunk:"4.8 cu ft",campBattery:"~4–6% (mild/summer) · ~17–25% (no heat pump)",notes:"68\" floor length. Sloping rear roofline limits headroom near hatch. Frunk (4.8 cu ft) useful for valuables. Small step at seat hinge. Solo camping.",mattresses:["NEMO Eclipse All-Season","Sea to Summit Comfort Deluxe LW","Therm-a-Rest MondoKing 3D"],setup:"Fold rear seats. Frunk stores gear. Keep head toward rear window (better headroom there).",color:"#b03060"},
  bz4x:     {name:"Toyota bZ4X",    L:73,W:45,H:36,up:27.0,down:56.5,flat:"Small step",platform:false,camp:"No — leave climate on",maxMat:'71\"×43\"',frunk:"None",campBattery:"~4–7% (mild/summer) · ~15–22% (manual climate)",notes:"60/40 split folding seats. Small step at hinge (~0.5–1\"). 73\" max length. Adjustable deckboard helps level floor. Identical platform to Subaru Solterra.",mattresses:["NEMO Eclipse All-Season","Sea to Summit Comfort Deluxe LW","Therm-a-Rest MondoKing 3D"],setup:"Fold rear seats. Use adjustable deckboard (upper position) for near-flat floor. Solo pads best.",color:"#cc3300"},
  solterra: {name:"Subaru Solterra", L:73,W:45,H:36,up:24.0,down:63.5,flat:"Small step",platform:false,camp:"No — leave climate on",maxMat:'71\"×43\"',frunk:"None",campBattery:"~4–7% (mild/summer) · ~15–22% (manual climate)",notes:"Identical platform to Toyota bZ4X. Squared-off rear opening is easy to load. Standard AWD. Same sleep setup as bZ4X.",mattresses:["NEMO Eclipse All-Season","Sea to Summit Comfort Deluxe LW","Therm-a-Rest MondoKing 3D"],setup:"Same as bZ4X. Adjustable deckboard on many trims. Squared tail makes loading mattresses easier.",color:"#1a5c8a"},
  bolt:     {name:"Chevrolet Bolt EV",L:60,W:42,H:33,up:16.6,down:56.9,flat:"Small step",platform:true,camp:"No — leave climate on",maxMat:'58\"×40\"',frunk:"None",campBattery:"~5–8% (mild/summer) · ~25–35% (no heat pump — cold costly)",notes:"Shortest sleeping length of all 14 EVs (60\"). Very tight for anyone over 5\'8\". Budget hatchback. Best for shorter solo campers.",mattresses:["NEMO Eclipse All-Season","Sea to Summit Comfort Deluxe LW"],setup:"Fold rear seats. Platform helps with step. Solo only. Best paired with ultra-light thin pad.",color:"#cc6600"},
  equinox:  {name:"Chevrolet Equinox EV",L:68,W:45,H:35,up:22.0,down:57.2,flat:"Nearly flat",platform:false,camp:"No — leave climate on",maxMat:'66\"×43\"',frunk:"None",campBattery:"~4–6% (mild/summer) · ~13–19% (manual climate)",notes:"Dual-height cargo floor. 60/40 split seats. Practical mid-size EV at competitive price. Good balance of space and value.",mattresses:["NEMO Eclipse All-Season","Sea to Summit Comfort Deluxe LW","Therm-a-Rest MondoKing 3D"],setup:"Use upper cargo floor position for near-flat surface. No platform needed. Solo or slim couples.",color:"#c4a000"},

  kia_ev6:      {name:"Kia EV6",               L:65,W:43,H:26,up:24.4,down:50.2,flat:"Nearly flat",platform:false,camp:"✓ Utility Mode + V2L 3.6kW",maxMat:'63\"×41\"',frunk:"Small (glovebox-size)",campBattery:"~4–6% (mild/summer) · ~14–21% (cold winter)",notes:"Sport crossover with sloping roofline. 65\" usable length — tight for anyone over 5\'10\". V2L outputs 3.6kW, highest of any EV on this list. Good for powering a camp kitchen or heater externally.",mattresses:["NEMO Eclipse All-Season","Sea to Summit Comfort Deluxe LW"],setup:"Fold rear seats. Nearly flat floor. Solo pads only. Set Utility Mode — disables drive, runs HV battery for climate overnight. V2L adapter powers external heater or cooker.",color:"#cc3300"},
  ioniq6:       {name:"Hyundai Ioniq 6",        L:71,W:43,H:23,up:11.2,down:42.0,flat:"Small step",platform:false,camp:"✓ Utility Mode + V2L 3.6kW",maxMat:'69\"×41\"',frunk:"0.5 cu ft (cable storage)",campBattery:"~4–6% (mild/summer) · ~14–21% (cold winter)",notes:"Streamlined sedan body limits headroom to just 23\". Cannot sit up. Better length than Model 3 at 71\", same V2L 3.6kW as EV6. Small frunk for cables only. Solo camping viable for shorter sleepers.",mattresses:["NEMO Eclipse All-Season","Sea to Summit Comfort Deluxe LW"],setup:"Fold rear seats. Small step at hinge. Solo pads only. V2L for external gear. Not recommended for anyone over 5\'11\".",color:"#2a78d6"},
  model_x:      {name:"Tesla Model X",          L:74,W:51,H:40,up:20.0,down:88.0,flat:"Flat (rows 2+3 folded)",platform:false,camp:"✓ Camp Mode",maxMat:'74\"×50\" (80\" w/seat fwd)',frunk:"6.5 cu ft",campBattery:"~3–5% (mild/summer) · ~10–16% (cold winter)",notes:"3-row Tesla — 74\" standard (seats normal) | ~80\" with front seats slid forward. Our original 88\" was wrong. Falcon-wing doors make loading easy. Falcon-wing rear doors make loading a mattress very easy. 6.5 cu ft frunk. Remove or fold 2nd and 3rd rows for flat floor.",mattresses:["Exped MegaMat Duo 10","Luno AIR+FOAM Pro","NEMO Roamer Double","Therm-a-Rest MondoKing 3D"],setup:"Fold or remove 2nd and 3rd rows. Floor is nearly flat. Camp Mode all night. Frunk stores valuables separately. Falcon-wing doors — load mattress from either side.",color:"#0f6e56"},
  r1t:          {name:"Rivian R1T (Truck Bed)", L:54,W:50,H:20,up:0.0,down:0.0,flat:"Flat truck bed",platform:false,camp:"✓ Camp Mode",maxMat:'54\"×48\"',frunk:"11 cu ft Gear Tunnel",campBattery:"~2–4% (mild/summer) · ~7–12% (cold winter)",notes:"Unique EV truck camping — sleep in the bed under the powered tonneau. Bed dimensions: ~54\"L × 50\"W with tailgate up. Drop the tailgate for up to 84\" total length. Gear Tunnel (11 cu ft) stores gear separately. Camp Mode keeps climate all night.",mattresses:["Therm-a-Rest MondoKing 3D","NEMO Eclipse All-Season","Sea to Summit Comfort Deluxe LW"],setup:"Under tonneau: 54\" bed. Tailgate down: 84\" total. Gear Tunnel for shoes/valuables. Air mattress or foam pad in the bed. Camp Mode for climate overnight.",color:"#2a6e2a"},
  rivian_r2:    {name:"Rivian R2",              L:75,W:41,H:32,up:28.7,down:79.4,flat:"Nearly flat",platform:false,camp:"✓ Camp Mode",maxMat:'73\"×39\"',frunk:"5.2 cu ft",campBattery:"~4–6% (mild/summer) · ~14–20% (cold winter)",notes:"Compact Rivian — smaller than R1S but still capable. 29\" hatch opening limits what mattresses can be slid in. 5.2 cu ft frunk larger than Model Y. Camp Mode standard. Good for solo or slim couples.",mattresses:["NEMO Eclipse All-Season","Sea to Summit Comfort Deluxe LW","Therm-a-Rest MondoKing 3D"],setup:"Fold rear seats. Nearly flat floor. Note 29\" hatch opening — roll mattress tightly or use a packable pad. Camp Mode for overnight climate.",color:"#3a8e3a"},
  polestar2:    {name:"Polestar 2",             L:69,W:41,H:30,up:14.0,down:38.0,flat:"Small step",platform:false,camp:"No — leave climate on",maxMat:'67\"×39\"',frunk:"1.1 cu ft (small)",campBattery:"~4–6% (mild/summer) · ~14–20% (manual climate)",notes:"Premium hatchback — sportier but less practical than an SUV. 69\" usable length, narrow at 41\". Solo camping workable for shorter sleepers. Small frunk. No dedicated camp mode.",mattresses:["NEMO Eclipse All-Season","Sea to Summit Comfort Deluxe LW"],setup:"Fold rear seats. Small step at hinge — manageable without a platform. Solo narrow pads only. Leave climate on manually overnight.",color:"#1a1a1a"},
  cybertruck:   {name:"Tesla Cybertruck",       L:72,W:48,H:40,up:0.0,down:0.0,flat:"Flat truck bed",platform:false,camp:"✓ Camp Mode",maxMat:'72\"×46\"',frunk:"2.2 cu ft",campBattery:"~2–4% (mild/summer) · ~8–13% (cold winter)",notes:"Stainless steel truck bed: 72\"L × 48\"W. Camp Mode. 120V and 240V outlets. Electric tonneau cover. The vault-like sealed bed is weatherproof. Also usable for cabin sleeping with platform build.",mattresses:["Therm-a-Rest MondoKing 3D","NEMO Roamer Double","Sea to Summit Comfort Deluxe LW"],setup:"Bed camping: lay mattress on bed floor, close tonneau. Camp Mode for HVAC. 120V outlet powers electric blanket or fan. Fits 2 people with tailgate-down extension.",color:"#555"},
  f150_lightning:{name:"Ford F-150 Lightning",  L:64,W:52,H:35,up:0.0,down:0.0,flat:"Flat truck bed",platform:false,camp:"Yes (Pro Power Onboard)",maxMat:'63\"×50\"',frunk:"14.1 cu ft",campBattery:"~2–4% (mild/summer) · ~8–12% (cold winter)",notes:"Best powered campsite of any EV — 7.2kW Pro Power Onboard with 8× 120V + 1× 240V outlets. Massive 14.1 cu ft mega frunk. Bed: ~65\"L × 52\"W. V2L-style power to run almost anything on a campsite.",mattresses:["Therm-a-Rest MondoKing 3D","NEMO Roamer Double","Klymit Klymaloft Double"],setup:"Bed camping: mattress in bed, use tonneau for weather protection. 14.1 cu ft frunk for food/gear. Run lights, heater, coffee maker from 7.2kW outlets. Best base camp EV.",color:"#003399"},
  ariya:{name:"Nissan Ariya",L:72,W:47,H:36,up:30.0,down:72.0,flat:"Nearly flat",platform:false,camp:"Manual / app timer",maxMat:"72in x 47in (solo)",frunk:"None",campBattery:"~5-8% mild · ~16-24% cold",notes:"6 ft usable length with front seats forward. No Camp Mode — manage HVAC manually. Divide-N-Hide cargo system.",mattresses:["Therm-a-Rest MondoKing 3D","REI Westward Dreamer","FULI Japanese Shikibuton"],setup:"Fold 60/40 rear seats. Slide front seats forward. Manage climate manually overnight.",color:"#c41c21"},
  blazer_ev:{name:"Chevy Blazer EV",L:72,W:48,H:36,up:30.0,down:72.0,flat:"Nearly flat — slight step",platform:false,camp:"Manual HVAC only",maxMat:"72in x 48in (solo)",frunk:"None",campBattery:"~5-8% mild · ~16-24% cold",notes:"70-75in usable length with seats forward. Rear seats nearly flat with slight step. No Camp Mode or V2L.",mattresses:["Therm-a-Rest MondoKing 3D","Klymit Insulated Double V","FULI Japanese Shikibuton"],setup:"Fold 60/40 rear seats. Platform board smooths seat step. No Camp Mode — monitor battery overnight.",color:"#d4a017"},
  ioniq9:{name:"Hyundai Ioniq 9",L:85,W:54,H:41,up:30.0,down:85.0,flat:"Flat (3rd row removed)",platform:false,camp:"Relaxation Mode",maxMat:"85in x 54in est.",frunk:"Small frunk",campBattery:"~3-5% mild · ~10-16% cold",notes:"Full-size 3-row EV. 86.9 cu ft cargo. Est 85in x 54in sleeping (3rd row out). 3.6 kW V2L. Owner dimensions pending.",mattresses:["Exped MegaMat Duo 10","NEMO Roamer Double","HEST Dually Long"],setup:"Remove/fold 3rd row. 2nd row folds flat. Relaxation Mode + V2L. Low overnight drain.",color:"#003580"},
  trailseeker:{name:"Subaru Trailseeker",L:75,W:46,H:34,up:30.0,down:75.0,flat:"Fully flat",platform:false,camp:"Manual / 1500W outlet (Touring)",maxMat:"75in x 46in",frunk:"None",campBattery:"~5-8% mild · ~16-22% cold",notes:"Spec-confirmed 75in cargo length. Genuinely flat floor. Touring trim has 1500W AC outlet. 8.5in ground clearance.",mattresses:["Therm-a-Rest MondoKing 3D","REI Westward Dreamer","FULI Japanese Shikibuton"],setup:"Fold rear seats flat. Use Touring 1500W outlet for fan/cooler. No Camp Mode — manage HVAC manually.",color:"#006a4e"},
  vinfast_vf8:{name:"VinFast VF8",L:68,W:46,H:34,up:28.0,down:68.0,flat:"Nearly flat",platform:false,camp:"Camp Mode (lights + audio only)",maxMat:"68in x 46in est.",frunk:"None",campBattery:"~5-8% mild · ~18-26% cold",notes:"Camp Mode covers lights and audio — not HVAC. Dimensions estimated; verify before buying mattress.",mattresses:["Therm-a-Rest MondoKing 3D","Klymit Insulated Double V","FULI Japanese Shikibuton"],setup:"Fold rear seats. Activate Camp Mode for lights/audio. Manage climate manually. Bring rated sleeping bag.",color:"#00a651"},
  vinfast_vf9:{name:"VinFast VF9",L:78,W:50,H:37,up:28.0,down:78.0,flat:"Flat (3rd row folded)",platform:false,camp:"Camp Mode (lights + audio only)",maxMat:"78in x 50in est.",frunk:"None",campBattery:"~4-6% mild · ~13-20% cold",notes:"Three-row SUV. Camp Mode = lights/audio only. Est 78in x 50in (3rd row folded). Large 92 kWh battery for low overnight drain.",mattresses:["Exped MegaMat Duo 10","NEMO Roamer Double","Therm-a-Rest MondoKing 3D"],setup:"Fold 3rd and 2nd rows. Activate Camp Mode. Manage climate manually. Spacious for couples.",color:"#00a651"},
  vinfast_vf9: {name:"VinFast VF9", L:78, W:50, H:37,
    up:28.0, down:78.0, flat:"Flat (3rd row folded)",
    platform:false, camp:"✓ Camp Mode (lights + audio only)",
    maxMat:'78"×50" est.',
    frunk:"None",
    campBattery:"~4–6% (mild/summer) · ~13–20% (cold winter)",
    notes:"Three-row SUV. Camp Mode = lights + audio only. Est. 78in x 50in sleeping area (3rd row folded). Large 92 kWh battery for low overnight drain.",
    mattresses:["Exped MegaMat Duo 10","NEMO Roamer Double","Therm-a-Rest MondoKing 3D"],
    setup:"Fold 3rd and 2nd row seats. Activate Camp Mode. Manage climate manually. Spacious for couples.",
    color:"#00a651"},
};

function flatBadge(flat){
  if(flat.startsWith('✓')||flat.includes('Nearly flat')||flat.includes('Flat (3rd')||flat.includes('Multiflex')||flat.includes('Fully flat'))
    return '<span style="background:var(--success-bg);color:var(--success);padding:.2rem .45rem;border-radius:4px;font-size:.75rem;font-weight:600">'+flat+'</span>';
  if(flat.includes('needs'))
    return '<span style="background:var(--danger-bg);color:var(--danger);padding:.2rem .45rem;border-radius:4px;font-size:.75rem;font-weight:600">'+flat+'</span>';
  return '<span style="background:var(--warn-bg);color:var(--warn);padding:.2rem .45rem;border-radius:4px;font-size:.75rem;font-weight:600">'+flat+'</span>';
}
function campBadge(camp){
  return camp.startsWith('✓')
    ? '<span style="background:var(--success-bg);color:var(--success);padding:.2rem .45rem;border-radius:4px;font-size:.75rem;font-weight:600">'+camp+'</span>'
    : '<span style="background:var(--warn-bg);color:var(--warn);padding:.2rem .45rem;border-radius:4px;font-size:.75rem;font-weight:600">'+camp+'</span>';
}

function renderAllEVTable(){
  var tbody=document.getElementById('ev-all-tbody');
  if(!tbody)return;
  var order=['id_buzz_tourer','id_buzz','model_x','ev9','r1s','cybertruck','f150_lightning','r1t','model_y','rivian_r2','ix','ioniq5','mach_e','equinox','bz4x','solterra','ex40','id4','kia_ev6','ioniq6','model_3','bolt','polestar2'];
  tbody.innerHTML=order.map(function(key,i){
    var e=evProfiles[key];
    return '<tr style="'+(i%2===1?'background:rgba(248,249,250,.5)':'')+'">'+
      '<td style="padding:.8rem 1rem;border-bottom:1px solid var(--border);font-weight:600;cursor:pointer;color:var(--primary)" onclick="document.getElementById(\'ev-select\').value=\''+key+'\';showEVProfile(\''+key+'\')">'+e.name+'</td>'+
      '<td style="padding:.8rem 1rem;border-bottom:1px solid var(--border);text-align:center;font-weight:700">'+e.L+'"</td>'+
      '<td style="padding:.8rem 1rem;border-bottom:1px solid var(--border);text-align:center;font-weight:700">'+e.W+'"</td>'+
      '<td style="padding:.8rem 1rem;border-bottom:1px solid var(--border);text-align:center;font-weight:700;'+(e.H<25?'color:var(--warn)':e.H>50?'color:var(--success)':'')+'">'+e.H+'"</td>'+
      '<td style="padding:.8rem 1rem;border-bottom:1px solid var(--border);font-size:.85rem">'+e.maxMat+'</td>'+
      '<td style="padding:.8rem 1rem;border-bottom:1px solid var(--border);text-align:center">'+flatBadge(e.flat)+'</td>'+
      '<td style="padding:.8rem 1rem;border-bottom:1px solid var(--border);text-align:center">'+campBadge(e.camp)+'</td>'+
      '<td style="padding:.8rem 1rem;border-bottom:1px solid var(--border);text-align:center;font-weight:600">'+e.down+' cu ft</td>'+
      '<td style="padding:.8rem 1rem;border-bottom:1px solid var(--border);font-size:.82rem;color:var(--text2)">'+e.notes.substring(0,70)+'…</td>'+
    '</tr>';
  }).join('');
}

function showEVProfile(key){
  var panel=document.getElementById('ev-profiles-individual');
  var allDiv=document.getElementById('ev-profiles-all');
  if(!key){allDiv.style.display='block';panel.style.display='none';return;}
  var e=evProfiles[key];
  allDiv.style.display='none';
  panel.style.display='block';
  var matchedMats=mattresses.filter(function(m){return m[key]==='Good';});
  var matRows=matchedMats.length?matchedMats.map(function(m){
    return '<tr><td style="padding:.55rem .75rem;border-bottom:1px solid var(--border);font-weight:600;font-size:.85rem">'+m.name+'</td>'+
      '<td style="padding:.55rem .75rem;border-bottom:1px solid var(--border);font-size:.83rem">$'+m.price+'</td>'+
      '<td style="padding:.55rem .75rem;border-bottom:1px solid var(--border);font-size:.83rem">'+m.weight_lbs+' lbs</td>'+
      '<td style="padding:.55rem .75rem;border-bottom:1px solid var(--border);font-size:.83rem"><span class="rval '+rvClass(m.rvalue)+'">'+m.rvalue+'</span></td>'+
      '<td style="padding:.55rem .75rem;border-bottom:1px solid var(--border);font-size:.83rem">'+m.type+'</td></tr>';
  }).join(''):'<tr><td colspan="5" style="padding:.75rem;color:var(--text3);font-size:.85rem">No mattresses currently rated Good for this EV — check back soon.</td></tr>';

  panel.innerHTML='<div style="border:2px solid '+e.color+';border-radius:8px;overflow:hidden;margin-bottom:2rem">'+
    '<div style="background:'+e.color+';padding:1.25rem 1.5rem;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:.5rem">'+
      '<div><div style="color:rgba(255,255,255,.7);font-size:.72rem;font-weight:700;text-transform:uppercase;letter-spacing:.5px;margin-bottom:.2rem">EV Camping Profile</div>'+
      '<div style="color:#fff;font-size:1.3rem;font-weight:700">'+e.name+'</div></div>'+
      '<button onclick="showAllEVs()" style="background:rgba(255,255,255,.15);border:1px solid rgba(255,255,255,.4);color:#fff;border-radius:5px;padding:.5rem .9rem;font-size:.82rem;font-weight:600;cursor:pointer">← All EVs</button>'+
    '</div>'+
    '<div style="padding:1.5rem;background:#fff">'+
      '<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:1rem;margin-bottom:1.5rem">'+
        '<div style="background:var(--bg);border-radius:6px;padding:1rem;text-align:center"><div style="font-size:1.8rem;font-weight:700;color:'+e.color+'">'+e.L+'"</div><div style="font-size:.72rem;color:var(--text3);text-transform:uppercase;letter-spacing:.4px;font-weight:600;margin-top:.2rem">Length</div></div>'+
        '<div style="background:var(--bg);border-radius:6px;padding:1rem;text-align:center"><div style="font-size:1.8rem;font-weight:700;color:'+e.color+'">'+e.W+'"</div><div style="font-size:.72rem;color:var(--text3);text-transform:uppercase;letter-spacing:.4px;font-weight:600;margin-top:.2rem">Width</div></div>'+
        '<div style="background:var(--bg);border-radius:6px;padding:1rem;text-align:center"><div style="font-size:1.8rem;font-weight:700;color:'+(e.H<25?'var(--warn)':e.H>50?'var(--success)':e.color)+'">'+e.H+'"</div><div style="font-size:.72rem;color:var(--text3);text-transform:uppercase;letter-spacing:.4px;font-weight:600;margin-top:.2rem">Headroom</div></div>'+
        '<div style="background:var(--bg);border-radius:6px;padding:1rem;text-align:center"><div style="font-size:1.8rem;font-weight:700;color:'+e.color+'">'+e.down+'</div><div style="font-size:.72rem;color:var(--text3);text-transform:uppercase;letter-spacing:.4px;font-weight:600;margin-top:.2rem">Cu ft (down)</div></div>'+
      '</div>'+
      '<div style="display:grid;grid-template-columns:1fr 1fr;gap:.6rem;margin-bottom:1.25rem;font-size:.88rem">'+
        '<div style="display:flex;gap:.5rem"><span style="color:var(--text3);min-width:115px;font-weight:500">Max mattress:</span><strong>'+e.maxMat+'</strong></div>'+
        '<div style="display:flex;gap:.5rem;align-items:center"><span style="color:var(--text3);min-width:115px;font-weight:500">Floor:</span>'+flatBadge(e.flat)+'</div>'+
        '<div style="display:flex;gap:.5rem;align-items:center"><span style="color:var(--text3);min-width:115px;font-weight:500">Camp Mode:</span>'+campBadge(e.camp)+'</div>'+
        '<div style="display:flex;gap:.5rem"><span style="color:var(--text3);min-width:115px;font-weight:500">Platform needed:</span><strong>'+(e.platform?'Yes — recommended':'No')+'</strong></div>'+
        '<div style="display:flex;gap:.5rem"><span style="color:var(--text3);min-width:115px;font-weight:500">Frunk:</span><strong>'+e.frunk+'</strong></div>'+
        '<div style="display:flex;gap:.5rem"><span style="color:var(--text3);min-width:115px;font-weight:500">Battery drain:</span><strong>'+e.campBattery+'</strong></div>'+
      '</div>'+
      '<div style="background:var(--bg);border-radius:6px;padding:1rem 1.1rem;margin-bottom:1rem;font-size:.9rem;color:var(--text2)">'+e.notes+'</div>'+
      '<div style="background:rgba(15,110,86,0.06);border-left:3px solid var(--primary);border-radius:4px;padding:.85rem 1rem;margin-bottom:1.5rem;font-size:.88rem"><strong>Setup tip:</strong> '+e.setup+'</div>'+
      '<h4 style="font-size:.8rem;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:var(--text3);margin-bottom:.65rem">Mattresses Rated Good for This EV</h4>'+
      '<div style="border:1px solid var(--border);border-radius:6px;overflow:hidden;margin-bottom:1rem">'+
        '<table style="width:100%;border-collapse:collapse;font-size:.88rem">'+
          '<thead><tr style="background:var(--bg)">'+
            '<th style="padding:.6rem .75rem;text-align:left;font-weight:600;border-bottom:2px solid var(--border)">Mattress</th>'+
            '<th style="padding:.6rem .75rem;text-align:left;font-weight:600;border-bottom:2px solid var(--border)">Price</th>'+
            '<th style="padding:.6rem .75rem;text-align:left;font-weight:600;border-bottom:2px solid var(--border)">Weight</th>'+
            '<th style="padding:.6rem .75rem;text-align:left;font-weight:600;border-bottom:2px solid var(--border)">R-Value</th>'+
            '<th style="padding:.6rem .75rem;text-align:left;font-weight:600;border-bottom:2px solid var(--border)">Type</th>'+
          '</tr></thead>'+
          '<tbody>'+matRows+'</tbody>'+
        '</table>'+
      '</div>'+
      '<button onclick="showPage(\'compare\');onEVSelect(\''+key+'\');document.getElementById(\'f-vehicle\').value=\''+key+'\'" style="background:'+e.color+';color:#fff;border:none;border-radius:5px;padding:.75rem 1.25rem;font-size:.88rem;font-weight:600;cursor:pointer">Filter Comparison Table for '+e.name+' →</button>'+
    '</div>'+
  '</div>';
  panel.scrollIntoView({behavior:'smooth',block:'start'});
}

function showAllEVs(){
  document.getElementById('ev-select').value='';
  document.getElementById('ev-profiles-individual').style.display='none';
  document.getElementById('ev-profiles-all').style.display='block';
}

function viewFullEVProfile(){
  if(!currentEV) return;
  // 1. Navigate to Guides page
  showPage('guides');
  // 2. Activate the EV Dimensions tab
  const tabBtn = document.getElementById('tab-btn-ev-dims');
  document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
  document.querySelectorAll('.tab-pane').forEach(p => p.classList.remove('active'));
  if(tabBtn) tabBtn.classList.add('active');
  const pane = document.getElementById('t-ev-dims');
  if(pane) pane.classList.add('active');
  // 3. Set the EV select and show the profile
  const sel = document.getElementById('ev-select');
  if(sel) sel.value = currentEV;
  showEVProfile(currentEV);
}
document.addEventListener('DOMContentLoaded',renderAllEVTable);


